en:
  languageName: English
  weight: 1
      
zh-hans:
  baseURL: https://zh-hans.hbstack.dev/
  languageName: 简体中文
  weight: 2
  title: HB 框架
      
zh-hant:
  baseURL: https://zh-hant.hbstack.dev/
  languageName: 繁體中文
  weight: 3
  title: HB 框架
