main:
  - name: Docs
    identifier: docs
    weight: 1
    params:
      icon:
        vendor: bs
        name: book

  - name: Support
    identifier: support
    weight: 100
    url: https://github.com/hbstack/
    params:
      header: The HB support community.
      icon:
        vendor: font-awesome-solid
        name: headset

  - name: Mastodon
    parent: support
    url: https://techhub.social/@hbstack
    weight: 100
    params:
      description: Follow our Mastodon account for getting latest updates.
      icon:
        vendor: simple
        name: mastodon

  - name: GitHub
    parent: support
    url: https://github.com/hbstack/
    weight: 1
    params:
      icon:
        vendor: fab
        name: github
      description: The code repository.

  - name: Discussion
    parent: support
    url: https://github.com/orgs/hbstack/discussions/
    weight: 2
    params:
      icon:
        vendor: font-awesome-regular
        name: comments
        color: green
      description: Ask questions and share your ideas.

  - name: Bug Report
    parent: support
    url: https://github.com/orgs/hbstack/discussions/new?category=issues-and-bugs
    weight: 3
    params:
      icon:
        vendor: font-awesome-solid
        name: bug
        color: red
      description: Tell us about a bug or issue.

  - name: Feature Request
    parent: support
    url: https://github.com/orgs/hbstack/discussions/new?category=ideas
    weight: 4
    params:
      icon:
        vendor: font-awesome-regular
        name: lightbulb
        color: orange
      description: Suggest new or updated features.

footer:
  - name: Projects
    identifier: projects
    weight: 10
    params:
      icon:
        vendor: bootstrap
        name: boxes
        color: skyblue
  - name: HugoPress
    parent: projects
    weight: 11
    url: https://hugomods.com/en/docs/hugopress/
    params:
      icon:
        vendor: simple-icons
        name: hugo
        color: "#FF4088"
  - name: Hugo Docker Images
    parent: projects
    weight: 12
    url: https://hugomods.com/en/docs/docker/
    params:
      icon:
        vendor: simple-icons
        name: docker
        color: "#2496ED"
  - name: Icons
    parent: projects
    weight: 13
    url: https://hugomods.com/en/icons/
    params:
      icon:
        vendor: font-awesome-solid
        name: icons
        color: "#F76119"
  - name: SEO
    parent: projects
    weight: 14
    url: https://github.com/hugomods/seo/
    params:
      icon:
        vendor: font-awesome-solid
        name: magnifying-glass
        color: "#87CEEB"
  - name: Search
    parent: projects
    weight: 15
    url: https://hugomods.com/en/docs/search/
    params:
      icon:
        vendor: bootstrap
        name: search
        color: "#712cf9"
  - name: Bootstrap Shortcodes
    parent: projects
    weight: 16
    url: https://hugomods.com/en/bootstrap/
    params:
      icon:
        vendor: bootstrap
        name: code-square
        color: "#712cf9"

  - name: Support
    identifier: support
    weight: 40
    url: https://github.com/hbstack/
    params:
      icon:
        vendor: font-awesome-solid
        name: headset
        color: "#0A5DB9"
  - name: GitHub
    parent: support
    url: https://github.com/hbstack/
    weight: 41
    params:
      icon:
        vendor: font-awesome-brands
        name: github
  - name: Discussion
    parent: support
    url: https://github.com/orgs/hbstack/discussions/
    weight: 42
    params:
      icon:
        vendor: far
        name: comments
        color: green
  - name: Bug Report
    parent: support
    url: https://github.com/orgs/hbstack/discussions/new?category=issues-and-bugs
    weight: 43
    params:
      icon:
        vendor: font-awesome-solid
        name: bug
        color: red

  - name: Feature Request
    parent: support
    url: https://github.com/orgs/hbstack/discussions/new?category=ideas
    weight: 44
    params:
      icon:
        vendor: font-awesome-regular
        name: lightbulb
        color: orange
