title = "HB (Hugo Bootstrap) Framework"
copyright = "Copyright Â© 2022-{year} [COMPANY](https://example.com). All Rights Reserved."

[params]
description = "Fast, responsive, flexible, modular, open source and feature-rich Hugo Bootstrap Framework."

[params.hb.footer]
powered_by = true
